SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `todo_app` DEFAULT CHARACTER SET utf8 ;
USE `todo_app`;



CREATE TABLE IF NOT EXISTS `user`(
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
    );
CREATE UNIQUE INDEX `ix_user_email` ON `user` (`email`);



CREATE TABLE IF NOT EXISTS `task` (
    `id` BIGINT  NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    `status` BOOLEAN NOT NULL,
    `user_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`)
)

    ENGINE = InnoDB
    AUTO_INCREMENT = 1002;

ALTER TABLE `task`
    ADD CONSTRAINT fk_task_user FOREIGN KEY (`user_id`) REFERENCES `user`(`id`);

CREATE INDEX `ix_task_status` ON `task` (`status`);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
